services:
    app.mail.sender:
        class: AppBundle\Mail\Sender
        arguments:
            - '@mailer'
            - '@translator'
            - '@templating'
            - '%app.contact_form.sender_email%'
            - '%app.contact_form.recipient_email%'
